version: '3.7'
services:
  nginx:
    image: nginx:alpine
    hostname: 'nginx'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./nginx/logs/:/var/log/nginx/
    ports:
      - '8080:80'
    depends_on:
      - api
    restart: always

  api:
    build: ./
    ports:
      - '5000'
    depends_on:
      - db
    links:
      - db
    restart: always

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
   #   - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  #  api:
  #    container_name: quotes-api
  #    build:
  #      context: ./
  #      target: production
  #    image: quotes-api
  #    depends_on:
  #      - db
  #    ports:
  #      - 3000:3000
  #    environment:
  #      NODE_ENV: production
  #      DB_HOST: db
  #      DB_PORT: 5432
  #      DB_USER: postgres
  #      DB_PASSWORD: postgres
  #      DB_NAME: postgres
  #    links:
  #      - db
  #    volumes:
  #      - './:/src'
volumes:
    db:
      driver: local